#! /bin/sh

set -ex

lb config --bootappend-live "boot=live locales=fr_FR.UTF-8 keyboard-layouts=fr" --mode debian --system live --distribution bookworm --archive-areas "main contrib non-free non-free-firmware" --binary-images iso-hybrid --bootloaders "syslinux"

mkdir -p config/includes.chroot_after_packages/etc/
cp crontab config/includes.chroot_after_packages/etc/
chmod +777 config/includes.chroot_after_packages/etc/crontab

mkdir -p config/includes.chroot_after_packages/etc/skel/
cp monscript.sh config/includes.chroot_after_packages/etc/skel/
chmod +777 config/includes.chroot_after_packages/etc/skel/monscript.sh

mkdir -p config/includes.chroot_after_packages/etc/skel/config/obs-studio
cp obs-studio-config/config config/includes.chroot_after_packages/etc/skel/config/obs-studio/basic/profiles/untitled/basic.ini
chmod +777 config/includes.chroot_after_packages/etc/skel/config/obs-studio/basic/profiles/untitled/basic.ini
cp obs-studio-config/config config/includes.chroot_after_packages/etc/skel/config/obs-studio/gloabal.ini
chmod +777 config/includes.chroot_after_packages/etc/skel/config/obs-studio/gloabal.ini

echo task-cinnamon-desktop > config/package-lists/desktop.list.chroot
echo obs-studio >> config/package-lists/desktop.list.chroot
echo git >> config/package-lists/desktop.list.chroot
echo pip >> config/package-lists/desktop.list.chroot

cp --recursive syslinux/ config/bootloaders
cp --recursive syslinux_common/ config/bootloaders

lb build
